export const metadata = {
  title: "Privacy Policy — JobAgent",
  description: "Privacy Policy for JobAgent AI job application automation platform",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-200">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: March 30, 2026</p>

        <div className="space-y-10 text-sm leading-relaxed">
          {/* ── Introduction ─────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Introduction</h2>
            <p>
              JobAgent (&quot;we,&quot; &quot;our,&quot; or &quot;the Service&quot;) is an AI-powered job hunting
              platform available at{" "}
              <a href="https://job-agent-umber.vercel.app" className="text-blue-400 hover:underline">
                https://job-agent-umber.vercel.app
              </a>
              . This Privacy Policy explains how we collect, use, store, and protect your personal
              information when you use our Service.
            </p>
            <p className="mt-2">
              By using JobAgent, you agree to the practices described in this policy. If you do not
              agree, please do not use the Service.
            </p>
          </section>

          {/* ── Data We Collect ──────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Data We Collect</h2>

            <h3 className="font-medium text-gray-300 mt-4 mb-2">2.1 Account Information</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Google account name and email address (via Google OAuth sign-in)</li>
              <li>Session identifiers for anonymous users who do not sign in</li>
            </ul>

            <h3 className="font-medium text-gray-300 mt-4 mb-2">2.2 Resume Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Resume files you upload (PDF)</li>
              <li>Parsed resume data: name, email, phone, skills, work experience, education</li>
            </ul>

            <h3 className="font-medium text-gray-300 mt-4 mb-2">2.3 Job Application Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Job titles, companies, and URLs you apply to</li>
              <li>Cover letters and application materials generated by the Service</li>
              <li>Application statuses and tracking history</li>
              <li>Cold outreach emails sent through the Service</li>
            </ul>

            <h3 className="font-medium text-gray-300 mt-4 mb-2">2.4 Gmail Data (Optional)</h3>
            <p className="mb-2">
              If you choose to connect your Gmail account, we access your inbox in{" "}
              <strong className="text-white">read-only mode</strong> to scan for job-related emails
              only. Specifically, we look for:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Application confirmation emails</li>
              <li>Interview invitations</li>
              <li>Rejection notifications</li>
              <li>Offer letters</li>
              <li>Recruiter outreach messages</li>
            </ul>
            <p className="mt-2">
              We do <strong className="text-white">not</strong> read, store, or process any emails
              unrelated to job applications. Non-job-related emails are classified as
              &quot;irrelevant&quot; and immediately discarded.
            </p>

            <h3 className="font-medium text-gray-300 mt-4 mb-2">2.5 Usage Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Chat commands and agent interactions</li>
              <li>Audit logs of sensitive actions (applications submitted, emails sent)</li>
              <li>IP addresses and timestamps for security monitoring</li>
            </ul>
          </section>

          {/* ── How We Use Your Data ─────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Data</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>To search for and score job listings against your resume</li>
              <li>To generate tailored cover letters, cold emails, and application materials</li>
              <li>To track your job application statuses and history</li>
              <li>To scan Gmail for job-related email updates (if connected)</li>
              <li>To send follow-up emails to recruiters on your behalf</li>
              <li>To maintain audit logs for security and compliance</li>
              <li>To improve the Service and fix bugs</li>
            </ul>
          </section>

          {/* ── Google API Limited Use Disclosure ────────────────── */}
          <section className="border border-blue-500/30 rounded-lg p-5 bg-blue-500/5">
            <h2 className="text-lg font-semibold text-white mb-3">
              4. Google API Services — Limited Use Disclosure
            </h2>
            <p className="mb-3">
              JobAgent&apos;s use and transfer of information received from Google APIs adheres to the{" "}
              <a
                href="https://developers.google.com/terms/api-services-user-data-policy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 hover:underline"
              >
                Google API Services User Data Policy
              </a>
              , including the Limited Use requirements.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Limited use:</strong> Gmail data is used exclusively
                to provide job application tracking features within JobAgent. It is not used for any
                other purpose.
              </li>
              <li>
                <strong className="text-white">No advertising:</strong> Gmail data is never used to
                serve advertisements or for any advertising-related purpose.
              </li>
              <li>
                <strong className="text-white">No sale or transfer:</strong> Gmail data is never
                sold, rented, leased, or transferred to any third party, except as necessary to
                provide or improve the Service, comply with applicable law, or as part of a merger
                or acquisition with continued confidentiality protections.
              </li>
              <li>
                <strong className="text-white">No human access:</strong> Gmail data is processed
                entirely by automated systems (AI classification models). No humans read, review, or
                access your Gmail content.
              </li>
              <li>
                <strong className="text-white">Read-only access:</strong> We request only{" "}
                <code className="bg-gray-800 px-1 rounded text-xs">gmail.readonly</code> scope. We
                cannot send, delete, or modify your emails.
              </li>
            </ul>
          </section>

          {/* ── Third-Party Services ─────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Third-Party Services</h2>
            <p className="mb-3">
              We use the following third-party services to operate JobAgent. Your data is shared with
              these services only as necessary to provide the Service:
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-gray-700 text-gray-400">
                    <th className="py-2 pr-4">Service</th>
                    <th className="py-2 pr-4">Purpose</th>
                    <th className="py-2">Data Shared</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-800">
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Google OAuth</td>
                    <td className="py-2 pr-4">Authentication, Gmail access</td>
                    <td className="py-2">Google account email, OAuth tokens</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Supabase</td>
                    <td className="py-2 pr-4">Database, token storage</td>
                    <td className="py-2">All user data (encrypted at rest)</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Anthropic (Claude)</td>
                    <td className="py-2 pr-4">AI agent orchestration</td>
                    <td className="py-2">Resume text, job descriptions, chat commands</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">OpenAI (GPT-4o mini)</td>
                    <td className="py-2 pr-4">Job scoring, form mapping</td>
                    <td className="py-2">Resume skills, job descriptions</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Google (Gemini)</td>
                    <td className="py-2 pr-4">Email drafting, cover letters</td>
                    <td className="py-2">Resume summary, job context</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Adzuna</td>
                    <td className="py-2 pr-4">Job search</td>
                    <td className="py-2">Search queries (job title, location)</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">JSearch (RapidAPI)</td>
                    <td className="py-2 pr-4">Job aggregation</td>
                    <td className="py-2">Search queries (job title, location)</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Resend</td>
                    <td className="py-2 pr-4">Email delivery</td>
                    <td className="py-2">Recipient email, email content</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 text-gray-300">Vercel</td>
                    <td className="py-2 pr-4">Hosting, serverless functions</td>
                    <td className="py-2">Request logs, IP addresses</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mt-3">
              We do not sell your personal data to any third party. Data is shared with the services
              above only to the extent required to provide the features you use.
            </p>
          </section>

          {/* ── Data Security ────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Data Security</h2>
            <p className="mb-3">
              We implement industry-standard security measures to protect your data:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong className="text-white">Encryption in transit:</strong> All data is
                transmitted over HTTPS/TLS
              </li>
              <li>
                <strong className="text-white">Encryption at rest:</strong> Database storage is
                encrypted via Supabase (AES-256)
              </li>
              <li>
                <strong className="text-white">Access controls:</strong> API keys and secrets are
                stored as environment variables, never in source code
              </li>
              <li>
                <strong className="text-white">Input validation:</strong> All API inputs are
                validated and sanitized using schema validation (Zod)
              </li>
              <li>
                <strong className="text-white">Rate limiting:</strong> API endpoints are
                rate-limited to prevent abuse
              </li>
              <li>
                <strong className="text-white">Audit logging:</strong> All sensitive actions
                (applications, emails, data access) are logged with timestamps and actor
                identification
              </li>
              <li>
                <strong className="text-white">CORS protection:</strong> API endpoints restrict
                cross-origin access to authorized origins only
              </li>
              <li>
                <strong className="text-white">Authentication:</strong> Cron job endpoints require
                secret token verification
              </li>
            </ul>
          </section>

          {/* ── Data Retention ────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Data Retention</h2>
            <p className="mb-3">We retain your data according to the following schedule:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong className="text-white">Chat sessions:</strong> Automatically deleted after
                30 days of inactivity
              </li>
              <li>
                <strong className="text-white">Agent logs:</strong> Automatically deleted after 90
                days
              </li>
              <li>
                <strong className="text-white">Audit logs:</strong> Retained for 1 year (SOC2
                minimum), then automatically deleted
              </li>
              <li>
                <strong className="text-white">Application queue:</strong> Terminal items (applied,
                rejected, failed) deleted after 30 days
              </li>
              <li>
                <strong className="text-white">Resume data and applications:</strong> Retained until
                you request deletion
              </li>
              <li>
                <strong className="text-white">Gmail OAuth tokens:</strong> Retained until you
                disconnect Gmail or request deletion
              </li>
            </ul>
            <p className="mt-2">
              Automated cleanup runs weekly to enforce these retention policies.
            </p>
          </section>

          {/* ── Your Rights ──────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Your Rights</h2>
            <p className="mb-3">You have the right to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong className="text-white">Access:</strong> Request a copy of all data we store
                about you
              </li>
              <li>
                <strong className="text-white">Correction:</strong> Request corrections to
                inaccurate data
              </li>
              <li>
                <strong className="text-white">Deletion:</strong> Request complete deletion of your
                account and all associated data
              </li>
              <li>
                <strong className="text-white">Disconnect Gmail:</strong> Revoke Gmail access at any
                time from the Emails page or your{" "}
                <a
                  href="https://myaccount.google.com/permissions"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-400 hover:underline"
                >
                  Google Account permissions
                </a>
              </li>
              <li>
                <strong className="text-white">Data portability:</strong> Request your data in a
                machine-readable format
              </li>
            </ul>
            <p className="mt-2">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:pgc67990@gmail.com" className="text-blue-400 hover:underline">
                pgc67990@gmail.com
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          {/* ── Incident Response ─────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Incident Response</h2>
            <p>
              In the event of a data breach that affects your personal information, we will:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Notify affected users via email within 72 hours of discovery</li>
              <li>Describe the nature of the breach and data involved</li>
              <li>Outline the steps taken to contain and remediate the breach</li>
              <li>Provide guidance on protective measures you can take</li>
              <li>Report to relevant authorities as required by applicable law</li>
            </ul>
          </section>

          {/* ── Children ─────────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Children&apos;s Privacy</h2>
            <p>
              JobAgent is not intended for use by individuals under the age of 16. We do not
              knowingly collect personal information from children. If you believe a child has
              provided us with personal data, please contact us and we will delete it promptly.
            </p>
          </section>

          {/* ── Changes ──────────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              11. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify users of material
              changes by posting the updated policy on this page with a revised &quot;Last
              updated&quot; date. Continued use of the Service after changes constitutes acceptance
              of the updated policy.
            </p>
          </section>

          {/* ── Contact ──────────────────────────────────────────── */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or your data, contact us at:
            </p>
            <div className="mt-3 p-4 rounded-lg bg-gray-900 border border-gray-800">
              <p className="text-white font-medium">JobAgent</p>
              <p>
                Email:{" "}
                <a href="mailto:pgc67990@gmail.com" className="text-blue-400 hover:underline">
                  pgc67990@gmail.com
                </a>
              </p>
              <p>
                Website:{" "}
                <a
                  href="https://job-agent-umber.vercel.app"
                  className="text-blue-400 hover:underline"
                >
                  https://job-agent-umber.vercel.app
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
